Backend/Controllers/AcademiaController.cs
using Backend.Data;
using Backend.Models;
using Backend.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Backend.Controllers
{
    public class AcademiaController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly AcademiaRepository academiaRepository;
        public AcademiaController(AcademiaRepository academiaRepository, ApplicationDbContext context)
        {
            this.academiaRepository = academiaRepository
;
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var academias = academiaRepository.Listar();
            return View(academias);
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        public IActionResult Editar(string cnpj)
        {
            var academia = academiaRepository.BuscarPorCnpj(cnpj);
            if (academia == null)
            {
                return NotFound();
            }

            var viewModel = new RedeUpdateModel
            {
                Cnpj = academia.Cnpj,
                Nome = academia.Nome,
                EnderecoId = academia.EnderecoId
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Editar(AcademiaUpdateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                academiaRepository.Editar(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }
        public async Task<IActionResult> ApagarConfirmacao(string id)
        {
            var pessoa = await context.Redes.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }
        public IActionResult Apagar(string cnpj)
        {
            try
            {
                bool apagado = academiaRepository.Apagar(cnpj);

                if (apagado) TempData["MensagemSucesso"] = "Contato apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu contato, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        
        [HttpPost]
        public IActionResult Criar(Academia academia)
        {
            academiaRepository.Adicionar(academia);
            return RedirectToAction("Index");
        }
    }
}

Backend/Controllers/LoginController.cs
using Backend.Data;
using Backend.Models;
using Backend.Repository;
using GymScheduleBackend.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Globalization;
using System.IdentityModel.Tokens.Jwt;
using System.Linq;
using System.Security.Claims;
using Microsoft.Extensions.Logging;

namespace Backend.Controllers
{
    [ApiController]
    [Route("/")]
    public class LoginController : Controller
    {
        private readonly PessoaRepository _pessoaRepository;

        public LoginController(PessoaRepository pessoaRepository)
        {
            _pessoaRepository = pessoaRepository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult LogarView(LoginModel loginModel)
        {
            var existingUser = _pessoaRepository.BuscarPorUsernameESenha(loginModel);
            if (existingUser == null)
                return RedirectToAction("Index", "Home");
            return View();
        }

        [HttpPost("login/token")]
        public ActionResult<dynamic> Logar([FromBody] LoginModel loginModel)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return BadRequest(ModelState);
                }

                var existingUser = _pessoaRepository.BuscarPorUsernameESenha(loginModel);
                if (existingUser == null)
                {
                    return NotFound("Usuário ou senha incorretos.");
                }

                var token = JwtService.GenerateToken(existingUser);
                var refreshToken = JwtService.GenerateRefreshToken();
                JwtService.SaveRefreshToken(existingUser.Username, refreshToken);
                CultureInfo.CurrentCulture = new CultureInfo("pt-BR");
                var expiredDateToken = token.expirationDate ?? DateTime.MinValue;
                DateTime timeUtc = expiredDateToken.ToUniversalTime();
                TimeZoneInfo destinyTimeZone = TimeZoneInfo.FindSystemTimeZoneById("E. South America Standard Time");
                DateTime expiredDateTokenBr = TimeZoneInfo.ConvertTimeFromUtc(timeUtc, destinyTimeZone);

                loginModel.Password = "";

                return new
                {
                    user = existingUser,
                    token = token.token,
                    refreshToken = refreshToken,
                    expiredDateToken = expiredDateTokenBr,
                };
            }
            catch (Exception)
            {
                // Logar o erro
                return StatusCode(500, "Ocorreu um erro interno no servidor.");
            }
        }
    }
}

Backend/Controllers/PessoaController.cs
using Backend.Data;
using Backend.Models;
using Backend.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Identity.Client;
using System;

namespace Backend.Controllers
{
    public class PessoaController : Controller
    {
        private readonly PessoaRepository pessoaRepository;

        private readonly ApplicationDbContext context;
        // Inicializa o EnderecoRepository através do construtor
        public PessoaController(PessoaRepository pessoaRepository, ApplicationDbContext context)
        {
            this.pessoaRepository = pessoaRepository;
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var pessoas = pessoaRepository.Listar();
            return View(pessoas);
        }

        public IActionResult Editar(string cpf)
        {
            var pessoa = pessoaRepository.BuscarPorCPF(cpf);
            if (pessoa == null)
            {
                return NotFound();
            }

            var viewModel = new PessoaUpdateModel
            {
                CPF = pessoa.CPF,
                Nome = pessoa.Nome,
                Sobrenome = pessoa.Sobrenome,
                UltimoNome = pessoa.UltimoNome,
                EnderecoId = pessoa.EnderecoId
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Editar(PessoaUpdateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                pessoaRepository.Editar(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }
        public IActionResult Apagar(string id)
        {
            try
            {
                bool apagado = pessoaRepository.Apagar(id);

                if (apagado) TempData["MensagemSucesso"] = "Contato apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu contato, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        public async Task<IActionResult> ApagarConfirmacao(int id)
        {
            var pessoa = await context.Pessoas.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }

        public IActionResult Cadastrar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Criar(Pessoa pessoa)
        {
            pessoaRepository.Adicionar(pessoa);
            return RedirectToAction("Index");
        }
    }
}

Backend/Controllers/RedeController.cs
using Backend.Data;
using Backend.Models;
using Backend.Repository;
using Microsoft.AspNetCore.Mvc;

namespace Backend.Controllers
{
    public class RedeController : Controller
    {
        private readonly ApplicationDbContext context;
        private readonly RedeRepository redeRepository;
        public RedeController(RedeRepository redeRepository, ApplicationDbContext context){
            this.redeRepository = redeRepository;
            this.context = context;
        }
        public async Task<IActionResult> Index()
        {
            var redes = redeRepository.Listar();
            return View(redes);
        }

        public IActionResult Editar(string cnpj)
        {
            var rede = redeRepository.BuscarPorCnpj(cnpj);
            if (rede == null)
            {
                return NotFound();
            }

            var viewModel = new RedeUpdateModel
            {
                Cnpj = rede.Cnpj,
                Nome = rede.Nome,
                EnderecoId = rede.EnderecoId
            };

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Editar(RedeUpdateModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                redeRepository.Editar(model);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }
        public IActionResult Cadastrar()
        {
            return View();
        }
        public async Task<IActionResult> ApagarConfirmacao(string id)
        {
            var pessoa = await context.Redes.FindAsync(id);
            if (pessoa == null)
            {
                return NotFound();
            }
            return View(pessoa);
        }
        public IActionResult Apagar(string cnpj)
        {
            try
            {
                bool apagado = redeRepository.Apagar(cnpj);

                if (apagado) TempData["MensagemSucesso"] = "Contato apagado com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar seu contato, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar seu contato, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }
        [HttpPost]
        public IActionResult Criar(Rede rede)
        {
            redeRepository.Adicionar(rede);
            return RedirectToAction("Index");
        }
    }
}

Backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de academias</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Backend.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rede" asp-action="Index">Redes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Academia" asp-action="Index">Academias</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Pessoas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Endereco" asp-action="Index">Endereços</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Login" asp-action="Index">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 ">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Todos os direitos reservados
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>