Backend/Models/Endereco.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

public class Endereco
{
    public int Id { get; set; }
    public string Estado { get; set; }
    public string Cidade { get; set; }
    public string Bairro { get; set; }
    public string Rua { get; set; }
    public int Numero { get; set; }
}

Backend/Controllers/EnderecoController.cs
using Backend.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Backend.Controllers
{
    public class EnderecoController : Controller
    {
        private readonly EnderecoRepository enderecoRepository;

        // Inicializa o EnderecoRepository através do construtor
        public EnderecoController(EnderecoRepository enderecoRepository)
        {
            this.enderecoRepository = enderecoRepository;
        }

        public IActionResult Index()
        {
            var enderecos = enderecoRepository.Listar();
            return View(enderecos);
        }
        public IActionResult Editar()
        {
            return View();
        }
        public IActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Endereco endereco)
        {
            enderecoRepository.Adicionar(endereco);
            return RedirectToAction("Index");
        }
    }
}

Backend/Views/Endereco/Cadastrar.cshtml
@model Endereco
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Cadastrar Endereco";
}

<div id="Editar_Pessoa" class="component" style="display:flex; flex-direction:row; justify-content:space-around">
    <h4>Cadastrar</h4>
    <a role="button" class="btn btn-primary" style="margin-right:5px;" asp-controller="Endereco" asp-action="Index">Voltar</a>

</div>
<div>
    <div style="display:flex; flex-direction:row; align-items:flex-end;">
    </div>
    <form asp-controller="Endereco" asp-action="Criar" method="post">
        <div class="form-group">
            <label for="Estado">Estado</label>
            <input type="text" asp-for="Estado" class="form-control" placeholder="Digite o Estado">
        </div>
        <div class="form-group">
            <label for="Cidade">Cidade</label>
            <input type="text" asp-for="Cidade" class="form-control" placeholder="Digite a Cidade">
        </div>
        <div class="form-group">
            <label for="Bairro">Bairro</label>
            <input type="text" asp-for="Bairro" class="form-control" placeholder="Digite o Bairro">
        </div>
        <div class="form-group">
            <label for="Rua">Rua</label>
            <input type="text" asp-for="Rua" class="form-control" placeholder="Digite a Rua">
        </div>
        <div class="form-group">
            <label for="Numero">Numero</label>
            <input type="number" asp-for="Numero" class="form-control" placeholder="Digite o Numero">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    </form>
</div>

Backend/Views/Endereco/Editar.cshtml
@model Endereco

@{
    ViewData["Title"] = "Editar";
}

<div class="component" style="display:flex; flex-direction:row; justify-content:space-around">
    <h4>Editar Endereço</h4>
    <a role="button" class="btn btn-primary" style="margin-right:5px;" asp-controller="Endereco" asp-action="Index">Voltar</a>
</div>
<div>
    <form asp-controller="Endereco" asp-action="Editar" method="post" class="form">
        <input type="hidden" asp-for="Estado" />
        <div class="form-group">
            <label for="estado" class="form-label">Estado</label>
            <input type="text" asp-for="Estado" class="form-control" placeholder="Digite o Estado">
            @Html.ValidationMessageFor(x => x.Estado)
        </div>

        <div class="form-group">
            <label for="Cidade" class="form-label">Cidade</label>
            <input type="text" asp-for="Cidade" class="form-control" placeholder="Digite a Cidade">
            @Html.ValidationMessageFor(x => x.Cidade)
        </div>

        <div class="form-group">
            <label for="bairro" class="form-label">Bairro</label>
            <input type="text" asp-for="Bairro" class="form-control" placeholder="Digite o Bairro">
            @Html.ValidationMessageFor(x => x.Bairro)
        </div>

        <div class="form-group">
            <label for="rua" class="form-label">Rua</label>
            <input type="text" asp-for="Rua" class="form-control" placeholder="Digite a Rua">
            @Html.ValidationMessageFor(x => x.Rua)
        </div>
        <div class="form-group">
            <label for="numero" class="form-label">Numero</label>
            <input type="number" asp-for="Numero" class="form-control" placeholder="Digite o Numero">
            @Html.ValidationMessageFor(x => x.Numero)
        </div>

        <button type="submit" class="btn btn-primary btn-block">Alterar</button>
        <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Endereco" role="button">Voltar</a>
    </form>
</div>

Backend/Views/Endereco/Index.cshtml
@model List<Endereco>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Listar adademia";
}

<div class="text-center">
    <div class="container">
        <div style="display:flex; flex-direction:row; justify-content:space-around;">
            <h4>Endereços</h4>
            <a class="btn btn-primary" style="margin-right:5px;" asp-controller="Endereco" asp-action="Cadastrar">Cadastrar</a>
        </div>
    </div>
</div>
<!-- Listar Academia -->
<div id="Listar_Endereco" style="display: flex;flex-direction:column;">
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Bairro</th>
                <th scope="col">CNPJ</th>
                <th scope="col">Endereço</th>
                <th scope="col">Rede</th>
                <th scope="col"></th>
            </tr>
        </thead>
            <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var endereco in Model)
                {
                    <tr>
                        <th scope="row">@endereco.Bairro</th>
                        <td>@endereco.Bairro</td>
                        <td>@endereco.Estado</td>
                        <td>@endereco.Cidade</td>
                        <td>@endereco.Rua</td>
                        <td>@endereco.Numero</td>
                        @* <td>@endere.Sobrenome</td>
                        <td>@endere.UltimoNome</td>
                        <td>@endere.Username</td>
                        <td>@endere.EnderecoId</td>
                        <td>@endere.RoleName</td> *@
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Edereco" asp-route-id="@endereco.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Edereco" asp-route-id="@endereco.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum Edereço encontrado</td></tr>
            }
        </tbody>
    </table>
</div>